# Generated by Django 5.1.3 on 2024-12-07 10:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback_table',
            name='date',
            field=models.DateField(),
        ),
        migrations.CreateModel(
            name='student_system_allocate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('STUD_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MyApp.student_table')),
                ('SYSTEM_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MyApp.system_table')),
            ],
        ),
    ]
