# Generated by Django 5.1.3 on 2024-12-09 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0002_alter_feedback_table_date_student_system_allocate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student_table',
            name='roll_no',
            field=models.CharField(max_length=100),
        ),
    ]
