# Generated by Django 5.1.4 on 2024-12-24 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0004_alter_lab_assistant_table_phone_no_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lab_assistant_table',
            name='dob',
            field=models.DateField(max_length=100),
        ),
    ]
