# Generated by Django 5.1.4 on 2025-01-29 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0005_alter_lab_assistant_table_dob'),
    ]

    operations = [
        migrations.CreateModel(
            name='memory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_memory', models.CharField(max_length=500)),
                ('avail_memory', models.CharField(max_length=500)),
                ('used_memory', models.CharField(max_length=500)),
                ('memory_percent', models.CharField(max_length=500)),
            ],
        ),
        migrations.AlterField(
            model_name='lab_table',
            name='Lab_no',
            field=models.IntegerField(),
        ),
    ]
