# Generated by Django 5.1.4 on 2025-02-07 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0008_log_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification_table',
            name='process',
            field=models.CharField(default='qwerty', max_length=100),
            preserve_default=False,
        ),
    ]
