# Generated by Django 5.1.3 on 2024-12-02 11:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='complaint_student_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complaint', models.CharField(max_length=500)),
                ('reply', models.CharField(max_length=500)),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='department_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department_name', models.CharField(max_length=100)),
                ('details', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='lab_assistant_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=100)),
                ('phone_no', models.IntegerField()),
                ('post', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('place', models.CharField(max_length=100)),
                ('pin', models.IntegerField()),
                ('qualification', models.CharField(max_length=100)),
                ('image', models.FileField(upload_to='')),
                ('dob', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='lab_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Lab_no', models.CharField(max_length=100)),
                ('Floor_no', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='login_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='course_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=100)),
                ('details', models.CharField(max_length=500)),
                ('DEPT', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MyApp.department_table')),
            ],
        ),
        migrations.CreateModel(
            name='assign_lab_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('LAB_ASST', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MyApp.lab_assistant_table')),
                ('LAB', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MyApp.lab_table')),
            ],
        ),
        migrations.AddField(
            model_name='lab_assistant_table',
            name='LOGIN',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MyApp.login_table'),
        ),
        migrations.CreateModel(
            name='staff_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('phone_no', models.BigIntegerField()),
                ('image', models.FileField(upload_to='')),
                ('semester', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=100)),
                ('post', models.CharField(max_length=100)),
                ('place', models.CharField(max_length=100)),
                ('pin', models.IntegerField()),
                ('dob', models.DateField()),
                ('qualification', models.CharField(max_length=100)),
                ('program_language', models.CharField(max_length=100)),
                ('COURSE', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MyApp.course_table')),
                ('LOGIN', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MyApp.login_table')),
            ],
        ),
        migrations.CreateModel(
            name='doubt_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doubt', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('reply', models.CharField(max_length=100)),
                ('image', models.FileField(upload_to='')),
                ('STUDENT', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MyApp.complaint_student_table')),
                ('STAFF', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MyApp.staff_table')),
            ],
        ),
        migrations.AddField(
            model_name='complaint_student_table',
            name='STAFF',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MyApp.staff_table'),
        ),
        migrations.CreateModel(
            name='student_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('studname', models.CharField(max_length=100)),
                ('roll_no', models.IntegerField()),
                ('image', models.FileField(upload_to='')),
                ('phone_no', models.BigIntegerField()),
                ('email', models.CharField(max_length=100)),
                ('semester', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=100)),
                ('post', models.CharField(max_length=100)),
                ('place', models.CharField(max_length=100)),
                ('pin', models.IntegerField()),
                ('dob', models.DateField()),
                ('qualification', models.CharField(max_length=100)),
                ('COURSE', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MyApp.course_table')),
                ('LOGIN', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MyApp.login_table')),
            ],
        ),
        migrations.CreateModel(
            name='feedback_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback', models.CharField(max_length=500)),
                ('date', models.CharField(max_length=100)),
                ('STAFF', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MyApp.staff_table')),
                ('STUDENT', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MyApp.student_table')),
            ],
        ),
        migrations.AddField(
            model_name='complaint_student_table',
            name='STUDENT',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MyApp.student_table'),
        ),
        migrations.CreateModel(
            name='subject_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=100)),
                ('semester', models.CharField(max_length=100)),
                ('syllabus', models.FileField(upload_to='')),
                ('COURSE', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MyApp.course_table')),
            ],
        ),
        migrations.CreateModel(
            name='subject_allocation_to_staff_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('STAFF', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MyApp.staff_table')),
                ('SUBJECT', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MyApp.subject_table')),
            ],
        ),
        migrations.CreateModel(
            name='exam_schedule_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('exam_name', models.CharField(max_length=100)),
                ('duration', models.CharField(max_length=100)),
                ('details', models.CharField(max_length=500)),
                ('syllabus', models.FileField(upload_to='')),
                ('STAFF', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MyApp.staff_table')),
                ('SUBJECT', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MyApp.subject_table')),
            ],
        ),
        migrations.CreateModel(
            name='system_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('system_no', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('processor', models.CharField(max_length=100)),
                ('RAM', models.CharField(max_length=100)),
                ('SSD', models.CharField(max_length=100)),
                ('HDD', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('LAB', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MyApp.lab_table')),
            ],
        ),
        migrations.CreateModel(
            name='screenshot_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('screenshot', models.FileField(upload_to='')),
                ('campic', models.FileField(upload_to='')),
                ('date', models.DateField()),
                ('status', models.CharField(max_length=100)),
                ('SYSTEM', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MyApp.system_table')),
            ],
        ),
        migrations.CreateModel(
            name='process_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('process', models.CharField(max_length=100)),
                ('SYSTEM', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MyApp.system_table')),
            ],
        ),
        migrations.CreateModel(
            name='notification_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('screenshot', models.FileField(upload_to='')),
                ('camera_image', models.FileField(upload_to='')),
                ('date', models.DateField()),
                ('status', models.CharField(max_length=100)),
                ('SYSTEM', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MyApp.system_table')),
            ],
        ),
        migrations.CreateModel(
            name='command_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('process', models.CharField(max_length=100)),
                ('SYSTEM', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MyApp.system_table')),
            ],
        ),
    ]
