# Generated by Django 5.1.4 on 2024-12-24 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0003_alter_student_table_roll_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lab_assistant_table',
            name='phone_no',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='lab_table',
            name='Lab_no',
            field=models.IntegerField(max_length=100),
        ),
    ]
