# Generated by Django 5.1.4 on 2025-01-29 11:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0006_memory_alter_lab_table_lab_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='memory',
            name='SYSTEM',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='MyApp.system_table'),
            preserve_default=False,
        ),
    ]
