# Generated by Django 5.1.4 on 2025-02-07 05:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0007_memory_system'),
    ]

    operations = [
        migrations.CreateModel(
            name='log_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login_time', models.TimeField()),
                ('logout_time', models.TimeField()),
                ('date', models.DateField()),
                ('SYSTEM_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MyApp.system_table')),
            ],
        ),
    ]
