from django.urls import path

from MyApp import views

urlpatterns = [
    path('',views.login),
    path('login_post',views.login_post),
    path('admin_add_course',views.admin_add_course),
    path('add_course_post',views.admin_add_course_post),
    path('admin_add_department',views.admin_add_department),
    path('admin_add_exam_schedule',views.admin_add_exam_schedule),

    path('admin_add_lab',views.admin_add_lab),
    path('admin_add_lab_post',views.admin_add_lab_post),

    path('admin_add_staff', views.admin_add_staff),
    path('admin_add_student',views.admin_add_student),
    path('admin_add_subject',views.admin_add_subject),
    path('admin_assign_lab',views.admin_assign_lab),
    path('admin_view_assigned_lab_post',views.admin_view_assigned_lab_post),
    path('admin_home_page',views.admin_home_page),
    path('admin_subject_allocation',views.admin_subject_allocation),
    path('admin_subject_allocation_post',views.admin_subject_allocation_post),
    path('admin_view_assigned_lab',views.admin_view_assigned_lab),
    path('admin_view_complaint',views.admin_view_complaint),
    path('send_reply/<id>',views.send_reply),
    path('send_reply_post',views.send_reply_post),
    path('admin_view_course', views.admin_view_course),
    path('admin_view_course_post', views.admin_view_course_post),
    path('admin_view_dept', views.admin_view_dept),
    path('admin_view_dept_post', views.admin_view_dept_post),
    path('admin_view_exam_schedule', views.admin_view_exam_schedule),
    path('admin_view_exam_schedule_post', views.admin_view_exam_schedule_post),
    path('admin_view_lab', views.admin_view_lab),
    path('admin_view_lab_post', views.admin_view_lab_post),
    path('admin_view_staff', views.admin_view_staff),
    path('admin_view_staff_post', views.admin_view_staff_post),
    path('admin_view_student', views.admin_view_student),
    path('admin_view_student_post', views.admin_view_student_post),
    path('admin_view_subject', views.admin_view_subject),
    path('admin_view_subject_post', views.admin_view_subject_post),
    path('admin_view_system_details', views.admin_view_system_details),
    path('admin_view_system_details_post', views.admin_view_system_details_post),
    path('admin_add_department_post', views.admin_add_department_post),
    path('edit_department/<id>', views.edit_department),
    path('delete_department/<id>', views.delete_department),
    path('edit_department_post', views.edit_department_post),
    # path('lab_assisstant_add_lab_subject', views.lab_assistant_add_lab_subject),
    path('lab_assistant_add_system', views.lab_assistant_add_system),
    path('lab_assistant_add_system_post', views.lab_assistant_add_system_post),
    path('allocate_system/<id>', views.allocate_system),
    path('allocate_system_post', views.allocate_system_post),
    path('lab_assistant_view_allocated_system', views.lab_assistant_view_allocated_system),

    path('lab_assistant_system_allocation', views.lab_assistant_system_allocation),
    path('lab_assistant_system_allocation_post', views.lab_assistant_system_allocation_post),
    # path('lab_assisstant_view_allocate', views.lab_assistant_view_allocate),
    # path('lab_assisstant_view_assigned_lab_subject_to_staff',views.lab_assistant_view_assigned_lab_subject_to_staff),
    path('lab_assistant_view_exam_schedule',views.lab_assistant_view_exam_schedule),
    path('lab_assistant_view_exam_schedule_post',views.lab_assistant_view_exam_schedule_post),
    path('lab_assistant_view_student',views.lab_assistant_view_student),
    path('lab_assistant_view_student_post',views.lab_assistant_view_student_post),
    path('lab_assistant_view_system_in_lab',views.lab_assistant_view_system_in_lab),
    path('lab_assistant_view_system_in_lab_post',views.lab_assistant_view_system_in_lab_post),
    path('delete_system/<id>',views.delete_system),
    path('edit_system/<id>',views.edit_system),
    path('edit_system_post',views.edit_system_post),
    path('staff_add_reply',views.staff_add_reply),
    path('staff_add_student', views.staff_add_student),
    path('staff_view_allocated_subject',views.staff_view_allocated_subject),
    path('staff_view_complaints', views.staff_view_complaints),
    path('staff_view_exam_schedule', views.staff_view_exam_schedule),
    path('staff_view_student', views.staff_view_student),
    path('delete_course/<id>', views.delete_course),
    path('edit_course/<id>', views.edit_course),
    path('edit_course_post', views.edit_course_post),
    path('delete_subject/<id>',views.delete_subject),
    path('admin_add_subject_post',views.admin_add_subject_post),
    path('edit_subject/<id>',views.edit_subject),
    path('edit_subject_post',views.edit_subject_post),
    path('delete_lab/<id>', views.delete_lab),
    path('edit_lab/<id>', views.edit_lab),
    path('edit_lab_post', views.edit_lab_post),
    path('admin_assign_lab_post', views.admin_assign_lab_post),
    path('delete_assign_lab/<id>',views.delete_assign_lab),
    path('edit_assign_lab/<id>',views.edit_assign_lab),
    path('edit_assign_lab_post',views.edit_assign_lab_post),
    path('admin_add_student_post',views. admin_add_student_post),
    path('admin_add_exam_schedule',views.admin_add_exam_schedule),
    path('admin_add_staff_post',views.admin_add_staff_post),
    path('delete_exam_schedule/<id>',views.delete_exam_schedule),
    path('admin_add_exam_schedule_post',views.admin_add_exam_schedule_post),
    path('edit_exam_schedule/<id>',views.edit_exam_schedule),
    path('edit_exam_schedule_post',views.edit_exam_schedule_post),
    path('delete_student/<id>',views.delete_student),
    path('edit_student/<id>',views.edit_student),
    path('edit_student_post',views.edit_student_post),
    path('admin_add_staff',views.admin_add_staff),
    path('delete_staff/<id>',views.delete_staff),
    path('edit_staff/<id>',views.edit_staff),
    path('edit_staff_post',views.edit_staff_post),
    path('admin_add_lab_assistant',views.admin_add_lab_assistant),
    path('admin_add_lab_assistant_post',views.admin_add_lab_assistant_post),
    path('admin_view_lab_assistant',views.admin_view_lab_assistant),
    path('admin_view_lab_assistant_post',views.admin_view_lab_assistant_post),
    path('delete_lab_assistant/<id>',views.delete_lab_assistant),
    path('edit_lab_assistant/<id>',views.edit_lab_assistant),
    path('edit_lab_assistant_post',views.edit_lab_assistant_post),
    path('lab_assistant_home_page',views.lab_assistant_home_page),
    path('lab_assistant_home_page_post',views.lab_assistant_home_page_post),
    path('lab_assistant_view_allocated_lab',views.lab_assistant_view_allocated_lab),
    path('lab_assistant_view_allocated_lab_post',views.lab_assistant_view_allocated_lab_post),
    path('staff_home_page',views.staff_home_page),
    path('staff_add_reply_post',views.staff_add_reply_post),
    path('staff_add_reply/<id>',views.staff_add_reply),
    path('staff_add_student',views.staff_add_student),
    path('staff_add_student_post',views.staff_add_student_post),
    path('staff_view_student',views.staff_view_student),
    path('staff_view_student_post',views.staff_view_student_post),
    path('staff_view_complaints',views.staff_view_complaints),
    path('staff_view_complaints_post',views.staff_view_complaints_post),
    path('staff_view_exam_schedule',views.staff_view_exam_schedule),
    path('staff_view_exam_schedule_post',views.staff_view_exam_schedule_post),
    path('staff_view_allocated_subject',views.staff_view_allocated_subject),
    path('staff_view_allocated_subject_post',views.staff_view_allocated_subject_post),
    path('staff_edit_student/<id>',views.staff_edit_student),
    path('staff_edit_student_post',views.staff_edit_student_post),
    path('staff_delete_student/<id>',views.staff_delete_student),



    path('student_view_profile',views.student_view_profile),
    path('view_lab',views.view_lab),
    path('view_subject',views.view_subject),
    path('view_exam_details',views.view_exam_details),
    path('view_system_info',views.view_system_info),
    path('send_complaint',views.send_complaint),
    path('student_send_feedback',views.student_send_feedback),
    path('view_reply',views.view_reply),
    path('send_feedback',views.send_feedback),
    path('android_login',views.android_login),
    path('viewstaff',views.viewstaff),
    path('user_view_profile',views.user_view_profile),
    path('update_profile',views.update_profile),
    path('forgot_password',views.forgot_password),
    path('Androidregistration',views.Androidregistration),
    path('view_coursename',views.view_coursename),
    path('view_gender',views.view_gender),
    path('insert_memory/',views.insert_memory),
    path('system_no',views.system_no),
    path('system_no_code',views.system_no_code),
    path('index',views.index),
    path('dw',views.dw),
    path('select',views.select),
    path('insprocess',views.insprocess),
    path('process',views.process),
    path('sd',views.sd),
    path('rs',views.rs),
    path('bgp',views.bgp),
    path('up',views.up),
    path('up1',views.up1),
    path('delete_memory',views.delete_memory),
    path('bgprocess/<id>',views.bgprocess),
    path('closefn/<id>',views.closefn),
    path('manage/<id>',views.manage),
    path('screenshot/<id>',views.screenshot),
    path('r_bgprocess/<id>',views.r_bgprocess),
    path('r_screenshot/<id>',views.r_screenshot),
    path('shutdown/<id>',views.shutdown),
    path('restart/<id>',views.restart),
    path('search',views.search),
    path('upn',views.upn),
    path('notification_details',views.notification_details),
    path('log_details',views.log_details),
    # path('admin_view_feedback',views.admin_view_feedback),
    path('staff_view_feedback',views.staff_view_feedback),



























]
